name-template: v$RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
exclude-contributors:
- github-actions
categories:
- title: New features
  labels:
  - enhancement
- title: Bug fixes
  labels:
  - bug
- title: Documentation
  labels:
  - docs
- title: Other changes
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: \<*_&
version-resolver:
  major:
    labels:
    - breaking-change
  minor:
    labels:
    - enhancement
  patch:
    labels:
    - bug
    - dependencies
  default: patch
template: |
  ## Changes since v$PREVIOUS_TAG

  $CHANGES

replacers:
- search: /@(renovate|dependabot(?:\[bot\])?)(?:,| |$)/gm
  replace: ''

autolabeler:
- label: docs
  files:
  - '*.md'
  title:
  - /docs/i
  branch:
  - /docs{0,1}\/.+/
- label: bug
  branch:
  - /fix\/.+/
  title:
  - /fix/i
- label: enhancement
  title:
  - /feat(\(.*\))?:/i
  branch:
  - /feat\/.+/
- label: breaking-change
  title:
  - /feat(\(.*\))?\!/i
  body:
  - /BREAKING-CHANGE/i