name: Release Drafter - prerelease

on:
  push:
    branches:
      - master

jobs:
  update_release_prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        with:
          config-name: release-drafter.prerelease.yml
          prerelease: true
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
