name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - master

  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      publish:
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-24.04
    steps:
    - uses: cchanche/release-drafter@master
        config-name: release-drafter.yml
        tag: ${{ inputs.tag }}
        version: ${{ inputs.version }}
        publish: ${{ inputs.publish }}